var jsonArray = [
     {
         "srcImg":"images/australia.png",
         "pais":"Australia",
         "codigo":"+61",
         "digitos":"8"
     },
     {
         "srcImg":"images/canada.png",
         "pais":"Canadá",
         "codigo":"+1",
         "digitos":"7"
     },
     {
         "srcImg":"images/china.png",
         "pais":"China",
         "codigo":"+86",
         "digitos":"11"
     },
     {
         "srcImg":"images/francia.png",
         "pais":"France",
         "codigo":"+33",
         "digitos":"9"
     },
     {
         "srcImg":"images/india.png",
         "pais":"India", 
         "codigo":"+91",
         "digitos":"8"
     },
     {
         "srcImg":"images/japon.jpg",
         "pais":"Japan",
         "codigo":"+81",
         "digitos":"7"
     },
     {
         "srcImg":"images/mexico.png",
         "pais":"Mexico",
         "codigo":"+52",
         "digitos":"10"
     },
     {
         "srcImg":"images/puertorico.png",
         "pais":"Puerto Rico",
         "codigo":"+1",
         "digitos":"7"
     },
     {
         "srcImg":"images/reinounido.jpg",
         "pais":"United Kingdom",
         "codigo":"+44",
         "digitos":"10"
     }
]